version : '3'
services:
  mapgis-xxx:
    build:
      context: ./${IMAGE_OS_NAME}-${IMAGE_ARCH}/mapgis/server
    image: mapgis/xxx-${IMAGE_OS_NAME}
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./mapgis/server/config:/mapgis/config
      - ./mapgis/server/logs:/mapgis/logs
      - ./mapgis/server/upload:/mapgis/upload
      - ./mapgis/server/data:/mapgis/data
      - ./mapgis/server/manager-apps:/mapgis/resource/static/manager-apps