# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: ${APP_PORT:8080}
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
    accesslog:
      # 开启访问日志
      enabled: ${TOMCAT_ACCESS_LOG_ENABLED:false}
      file-date-format: .yyyy-MM-dd
      suffix: .log
      prefix: access_log
      directory: tomcat_log
      pattern: common
    basedir: ./logs

# 日志配置
logging:
  level:
    org.springframework: warn

# Spring配置
spring:
  # 应用名称
  application:
    name: ${APP_NAME:${mapgis.product.full-name}-server}
  profiles:
    # 环境配置
    active: dev
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  mvc:
    static-path-pattern: /${mapgis.product.name}/static/**
  # 缓存配置
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  # jackson配置
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      # 格式化输出
      indent_output: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
  # flyway配置
  flyway:
    enabled: false
  # 配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    prefer-file-system-access: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zondy.mapgis.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: ${SWAGGER_DOC_ENABLED:true}
  # 标题
  title: ${SWAGGER_DOC_TIILE:MapGIS服务器产品 接口文档}
  # 描述
  description: ${SWAGGER_DOC_DESC:MapGIS服务器产品}
  version: @mapgis.boot.version@

# SpringDoc配置
springdoc:
  swagger-ui:
    # 开启Swagger UI界面
    enabled: ${swagger.enabled}
    path: /webjars/swagger-ui.html

# API前缀
api:
  path:
    services-prefix: /${mapgis.product.name}/rest/services
    manager-prefix: /${mapgis.product.name}/rest/manager

# 安全配置
security:
  # 验证码
  captcha:
    enabled: true
    # 验证码类型 math 数组计算 char 字符验证
    type: math
  # 防止XSS攻击
  xss:
    # 过滤开关
    enabled: true
    # 排除链接（多个用逗号分隔）
    excludes: ${api.path.manager-prefix}/system/notice
    # 匹配链接（多个用逗号分隔）
    urlPatterns: ${api.path.manager-prefix}/system/*,${api.path.manager-prefix}/monitor/*,${api.path.manager-prefix}/tool/*
  # 访问
  access:
    # 只读开关
    readonlyEnabled: ${SECURITY_ACCESS_READONLY_ENABLED:false}
  # 用户配置
  user:
    # 密码
    password:
      # 是否开启锁定
      lock-enabled: true
      # 最大错误次数
      max-retry-count: 5
      # 锁定时间（默认10分钟）
      lock-time: 10

# token配置
token:
  # 是否允许账户多终端同时登录（true允许 false不允许）
  soloLogin: ${SOLO_LOGIN_ENABLED:true}

# 本地文件上传
file:
  path: /upload
  prefix: /profile

# FastDFS配置
fdfs:
  domain: http://127.0.0.1
  soTimeout: 3000
  connectTimeout: 2000
  trackerList: 127.0.0.1:22122

# Minio配置
minio:
  url: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: test

# 第三方登录
justauth:
  enabled: true
  type:
    GITHUB:
      client-id: ${JUSTAUTH_GITHUB_CLIENT_ID}
      client-secret: ${JUSTAUTH_GITHUB_CLIENT_SECRET}
      redirect-uri: ${JUSTAUTH_GITHUB_REDIRECT_URI:http://127.0.0.1:${server.port}/${api.path.services-prefix}/auth/thirdLogin/callback/github}
    GITEE:
      client-id: ${JUSTAUTH_GITEE_CLIENT_ID}
      client-secret: ${JUSTAUTH_GITEE_CLIENT_SECRET}
      redirect-uri: ${JUSTAUTH_GITEE_REDIRECT_URI:http://127.0.0.1:${server.port}/${api.path.services-prefix}/auth/thirdLogin/callback/gitee}
  cache:
    type: default
  extend:
    enum-class: ${JUSTAUTH_CUSTOM_ENUM_CLASS:com.zondy.mapgis.auth.justauth.source.AuthCustomSource}
    authorize: ${JUSTAUTH_CUSTOM_AUTHORIZE_URL}
    access-token: ${JUSTAUTH_CUSTOM_ACCESS_TOKEN_URL}
    user-info: ${JUSTAUTH_CUSTOM_USER_INFO_URL}
    config:
      CUSTOM:
        request-class: ${JUSTAUTH_CUSTOM_REQUEST_CLASS:com.zondy.mapgis.auth.justauth.request.AuthCustomRequest}
        client-id: ${JUSTAUTH_CUSTOM_CLIENT_ID}
        client-secret: ${JUSTAUTH_CUSTOM_CLIENT_SECRET}
        redirect-uri: ${JUSTAUTH_CUSTOM_REDIRECT_URI:http://127.0.0.1:${server.port}/${api.path.services-prefix}/auth/thirdLogin/callback/custom}
        scopes: ${JUSTAUTH_CUSTOM_SCOPES}

# cas配置
cas:
  enabled: ${CAS_ENABLED:false}
  server:
    host:
      # cas服务端地址
      url: ${CAS_SERVER_HOST_URL:http://localhost:8888/cas}
      #cas服务端登录地址
      login_url: ${cas.server.host.url}/login
      #cas服务端登出地址 service参数后面跟就是需要跳转的页面/接口 这里指定的是cas客户端登录接口
      logout_url: ${cas.server.host.url}/logout?service=${cas.service.host.url}${cas.service.host.login_url}
  service:
    host:
      # cas客户端地址
      url: ${CAS_SERVICE_HOST_URL:http://localhost:${server.port}}
      # cas客户端地址登录地址
      login_url: ${CAS_SERVICE_LOGIN_URL:/login/cas}
      # cas客户端地址登出地址
      logout_url: ${CAS_SERVICE_LOGOUT_URL:/logout/cas}
    web:
      url: ${CAS_SERVICE_WEB_RUL:http://localhost:8000}