apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mapgis.fullname" . }}-redis
  labels:
    {{- include "mapgis.labels" . | nindent 4 }}-redis
    {{- include "mapgis.kindLabel" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mapgis.selectorLabels" . | nindent 6 }}-redis
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "mapgis.selectorLabels" . | nindent 8 }}-redis
    spec:
      containers:
      - name: {{ include "mapgis.fullname" . }}-redis
        image: {{ include "mapgis.imageRegistry" . }}/{{ include "mapgis.imageRedis" . }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1Gi
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - redis-cli select 1
          initialDelaySeconds: 10
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 5
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - redis-cli select 1
          initialDelaySeconds: 10
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 5
          periodSeconds: 30
        ports:
        - containerPort: 6379
          name: http
        env:
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: {{ include "mapgis.fullname" . }}-secret
              key: mapgis.redis.password
        command: ["redis-server", "--requirepass", "$(REDIS_PWD)"]
        volumeMounts:
        - name: {{ include "mapgis.fullname" . }}-redis-data
          mountPath: /data
      restartPolicy: Always
      volumes:
      - name: {{ include "mapgis.fullname" . }}-redis-data
        persistentVolumeClaim: 
          claimName: pvc-{{ include "mapgis.fullname" . }}-redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mapgis.fullname" . }}-redis
  labels:
    {{- include "mapgis.kindLabel" . | nindent 4 }}
spec:
  selector:
    {{- include "mapgis.selectorLabels" . | nindent 4 }}-redis
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ include "mapgis.fullname" . }}-redis-data
  labels:
    {{- include "mapgis.kindLabel" . | nindent 4 }}
spec:
  storageClassName: {{ include "mapgis.nfsStorageClassName" . }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi