apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "mapgis.kindLabel" . | nindent 4 }}
  name: {{ include "mapgis.fullname" . }}-nfs-client-provisioner
  annotations:
    scale: unscalable
    console: noconsole
    description: {{ include "mapgis.fullname" . }}-nfs-client-provisioner-description
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mapgis.fullname" . }}-nfs-client-provisioner
  template:
    metadata:
      labels:
        app: {{ include "mapgis.fullname" . }}-nfs-client-provisioner
    spec:
      {{- include "mapgis.imagePullSecret" . | nindent 6 }}
      serviceAccount: {{ include "mapgis.fullname" . }}-nfs-client-provisioner
      containers:
      - name: {{ include "mapgis.fullname" . }}-nfs-client-provisioner
        image: {{ include "mapgis.imageRegistry" . }}/{{ include "mapgis.imageNfsClientProvisioner" . }}
        imagePullPolicy: {{ include "mapgis.imagePullPolicy" . }}
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - name: nfs-client-root
          mountPath: /persistentvolumes
        env:
        - name: PROVISIONER_NAME
          value: {{ include "mapgis.fullname" . }}-nfs-client-provisioner
        - name: NFS_SERVER
          value: {{ include "mapgis.nfsServer" . }}
        - name: NFS_PATH
          value: {{ include "mapgis.nfsPath" . }}
      volumes:
      - name: nfs-client-root
        nfs:
          server: {{ include "mapgis.nfsServer" . }}
          path: {{ include "mapgis.nfsPath" . }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    {{- include "mapgis.kindLabel" . | nindent 4 }}
  name: {{ template "mapgis.nfsStorageClassName" . }}
provisioner: {{ include "mapgis.fullname" . }}-nfs-client-provisioner